export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
